services:
  - type: web
    name: ahp-platform
    env: node
    region: oregon
    plan: free
    buildCommand: npm run build:render
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_EMAIL
        value: aebon@naver.com
      - key: SUPPORT_EMAIL
        value: aebon@naver.com
      # DATABASE_URL은 Render Dashboard에서 수동으로 설정