version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ahp_db
      POSTGRES_USER: ahp_user
      POSTGRES_PASSWORD: ahp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ahp_network

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://ahp_user:ahp_password@postgres:5432/ahp_db
      JWT_SECRET: your-super-secret-jwt-key-here-change-in-production
      NODE_ENV: production
      PORT: 5000
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - ahp_network

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ahp_network
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api

volumes:
  postgres_data:

networks:
  ahp_network:
    driver: bridge